use crate::agent::conversation::{Message, Role};
pub struct CompactionConfig{pub large_output_threshold:usize,pub placeholder_keep_recent:usize,pub summary_max_chars:usize,pub emergency_keep:usize,pub max_context_tokens:usize}
impl Default for CompactionConfig{fn default()->Self{Self{large_output_threshold:5000,placeholder_keep_recent:6,summary_max_chars:200,emergency_keep:4,max_context_tokens:14000}}}
pub fn estimate_tokens(messages:&[Message])->usize{messages.iter().map(|m|m.content.len().div_ceil(4)).sum()}
pub fn compact_level0(messages:&mut[Message],config:&CompactionConfig)->Vec<String>{let mut off=Vec::new();for msg in messages.iter_mut(){if matches!(msg.role,Role::Tool)&&msg.content.len()>config.large_output_threshold{let h={use std::collections::hash_map::DefaultHasher;use std::hash::{Hash,Hasher};let mut ha=DefaultHasher::new();msg.content.hash(&mut ha);format!("{:x}",ha.finish())};let p=format!("/tmp/bonsai-out-{h}.txt");if std::fs::write(&p,&msg.content).is_ok(){let pv:String=msg.content.chars().take(200).collect();let l=msg.content.len();msg.content=format!("{pv}...\n[saved:{p}({l}c)]");off.push(p);}}}off}
pub fn compact_level1(messages:&mut[Message],config:&CompactionConfig){let t=messages.len();if t<=config.placeholder_keep_recent{return;}for msg in messages[..t-config.placeholder_keep_recent].iter_mut(){if matches!(msg.role,Role::Tool)&&msg.content.len()>50{let id=msg.tool_call_id.as_deref().unwrap_or("?");msg.content=format!("[prev:{id}]");}}}
pub fn compact_level2(messages:&mut[Message],config:&CompactionConfig){let t=messages.len();if t<=config.placeholder_keep_recent{return;}for msg in messages[..t-config.placeholder_keep_recent].iter_mut(){if matches!(msg.role,Role::Assistant)&&msg.content.len()>config.summary_max_chars{let s:String=msg.content.chars().take(config.summary_max_chars).collect();msg.content=format!("{s}...[summarized]");}}}
pub fn compact_level3(messages:&mut Vec<Message>,config:&CompactionConfig){if messages.len()<=config.emergency_keep+1{return;}let sys:Vec<Message>=messages.iter().filter(|m|matches!(m.role,Role::System)).cloned().collect();let rec:Vec<Message>=messages.iter().rev().take(config.emergency_keep).cloned().collect::<Vec<_>>().into_iter().rev().collect();messages.clear();messages.extend(sys);messages.extend(rec);}
pub fn compact_if_needed(messages:&mut Vec<Message>,config:&CompactionConfig)->(u8,Vec<String>){let off=compact_level0(messages,config);let mut lv=0u8;if estimate_tokens(messages)>config.max_context_tokens*3/4{compact_level1(messages,config);lv=1;}if estimate_tokens(messages)>config.max_context_tokens*9/10{compact_level2(messages,config);lv=2;}if estimate_tokens(messages)>config.max_context_tokens{compact_level3(messages,config);lv=3;}(lv,off)}
#[cfg(test)]mod tests{use super::*;fn mk(n:usize,sz:usize)->Vec<Message>{let mut v=vec![Message::system("s")];for i in 0..n{v.push(Message::user(format!("q{i}")));v.push(Message::assistant("x".repeat(sz)));v.push(Message::tool("y".repeat(sz),format!("t{i}")));}v}
#[test]fn t_tok(){assert_eq!(estimate_tokens(&[Message::user("hello world")]),3);}
#[test]fn t_l0(){let mut m=vec![Message::tool("x".repeat(10000),"b")];let o=compact_level0(&mut m,&CompactionConfig{large_output_threshold:5000,..Default::default()});assert_eq!(o.len(),1);for p in &o{std::fs::remove_file(p).ok();}}
#[test]fn t_l1(){let mut m=mk(10,100);compact_level1(&mut m,&CompactionConfig{placeholder_keep_recent:4,..Default::default()});assert!(m.iter().any(|x|x.content.contains("[prev:")));}
#[test]fn t_l2(){let mut m=mk(10,500);compact_level2(&mut m,&CompactionConfig{placeholder_keep_recent:4,summary_max_chars:100,..Default::default()});assert!(m.iter().any(|x|x.content.contains("[summarized]")));}
#[test]fn t_l3(){let mut m=mk(20,100);compact_level3(&mut m,&CompactionConfig{emergency_keep:4,..Default::default()});assert!(m.len()<=5);}
#[test]fn t_noop(){let mut m=vec![Message::user("hi")];let(lv,_)=compact_if_needed(&mut m,&CompactionConfig::default());assert_eq!(lv,0);}}
